# syntax = docker/dockerfile:1.0-experimental

# NOTE because of the special command line flags (e.g --secret) that need to be passed
# to the docker build process, we are not able to put these commands in the dockerfile 
# for the devcontainer
FROM quay.io/mhildenb/dev-demo-base:1.4

USER root

# install docker for use with kn func
RUN --mount=type=secret,id=myuser --mount=type=secret,id=mypass \
    subscription-manager register  --username=$(cat /run/secrets/myuser) \
    --password=$(cat /run/secrets/mypass) --auto-attach

RUN subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms

# Add support for Ansible (with python modules)
# With npm and gulp: add support for local antora based documentation building
RUN dnf install -y ansible python3 npm && npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3 \
    && npm rm --global npx && npm install --global npx && npm install --global gulp

# This whole RUN block is to support for docker for kn func and buildpacks
RUN microdnf -y install yum && yum install -y yum-utils && \
# install docker repo
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
# install docker client
    yum install -y docker-ce-cli && \
# cleanup packages and yum
    yum remove -y yum-utils && yum clean all && microdnf -y remove yum && microdnf clean all

RUN chown -R jboss /home/jboss

RUN subscription-manager unregister

USER jboss

# install in userspace, unclear how to install these python packages globally in the best way
RUN pip3 install openshift --user jboss

# Default DEMO_HOME directory
ENV DEMO_HOME /workspaces/cdc-data-monolith

