---
# Implement your Pre Workload deployment tasks here

- name: usercount debug
  debug:
    msg: "Debugging call"

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool