---
- name: Create DB Namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ db_project }}'
    state: present

- name: Create Data SQL ConfigMap
  k8s:
    state: present
    namespace: '{{ db_project }}'
    resource_definition: "{{ lookup('template', 'configmap-data-sql.yaml.j2') }}"

- name: Deploy MS SQL Server Database
  k8s:
    state: present
    namespace: '{{ db_project }}'
    resource_definition: "{{ lookup('template', 'mssql-server-linux.yaml.j2') }}"

- name: Wait for Database to Start
  k8s_info:
    kind: Deployment
    name: mssql-server-linux
    namespace: '{{ db_project }}'
    api_version: apps/v1
  register: mssql_resource
  until: >-
    (mssql_resource.resources is defined)
    and (mssql_resource.resources|length>0)
    and (mssql_resource.resources[0].status is defined)
    and (mssql_resource.resources[0].status.readyReplicas is defined)
    and (mssql_resource.resources[0].status.readyReplicas > 0)
  retries: 30
  delay: 10

- name: Configure CDC in Database
  shell: "oc -n {{ db_project }} exec deployment/mssql-server-linux -- /opt/mssql-tools/bin/sqlcmd -S mssql-server-linux -U sa -P 'Password!' -i /opt/workshop/data.sql"
  retries: 5
  delay: 2
  register: result
  until: result.rc == 0

- name: Check if App has been deployed
  k8s_info:
    kind: Deployment
    name: '{{ legacy_app_name }}'
    namespace: '{{ main_project }}'
    api_version: v1
  register: app_exists

# - name: Debug print resources
#   debug:
#     msg:
#     - "Resources are {{ app_exists.resources }}"

- name: Deploy Application
  block:
  - name: Deploy Legacy Application
    shell: "oc new-app {{ legacy_app_image }} --name '{{ legacy_app_name }}' \
            -e 'SERVER_NAME=mssql-server-linux.{{ db_project }}.svc' \
            -n {{ main_project }}"
  - name: Delete incorrect (automatically created) service
    shell: "oc delete service {{ legacy_app_name }} -n {{ main_project }}"
  - name: Correct Service
    shell: "oc expose deploy {{ legacy_app_name }} --port 8080 --target-port 8080 -n {{ main_project }}"
  - name: Create Legacy Application Route
    shell: "oc expose service {{ legacy_app_name }} --name=www -n {{ main_project }}"
  when: (app_exists.resources is undefined) or (app_exists.resources | length == 0)
